apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-lab18
  labels:
    app:  frontend-lab18
spec:
  selector:
    matchLabels:
      app:  frontend-lab18
  replicas: 1
  template:
    metadata:
      labels:
        app:  frontend-lab18
    spec:
      containers:
        - name:  frontend-lab18
          image: cloudclass-lab18/cicd-front
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
